export const volunteerList = [
	{
		_id: 1,
		title: '아동기초학습지도',
		content: '지구촌지역아동센터에서 초등학생 1~6학년 아이들 교육지도를 도와주실 봉사자를 모집합니다. 궁금한 사항 있으시면 언제든 연락주세요',
		centName: '지구촌지역아동센터',
		createdAt : '2023-05-30 14:00:00',
		statusName : '모집중',
		deadline : '2023-06-10 14:00:00',
		applyCount : 3,
		registerCount : 1,
		actTypeName : '교육지원',
		teenager : true,
		images : ['../../assets/images/volunteer1.jpg'],
		user_id : '1',
		updateAt : '2023-05-31 15:00:00',
	},
	{ 
		_id: 2,
		title: '다문화가정 요가교육',
		content: '갈월종합사회복지관 다문화가정 요가교육을 도와주실 봉사자를 모집합니다. 궁금한 사항 있으시면 언제든 연락주세요',
		centName: '갈월종합사회복지관',
		createdAt : '2023-05-30 14:00:00',
		statusName : '모집중',
		deadline : '2023-06-10 14:00:00',
		applyCount : 3,
		registerCount : 1,
		actTypeName : '교육지원',
		teenager : true,
		images : ['../../assets/images/volunteer1.jpg'],
		user_id : '1',
		updateAt : '2023-05-31 15:00:00',
	},
	{
		_id: 3,
		title: '뜨개질 수업',
		content: '영등포치매예방센터에서 뜨개질 수업을 도와주실 봉사자를 모집합니다. 궁금한 사항 있으시면 언제든 연락주세요',
		centName: '영등포치매예방센터',
		createdAt : '2023-05-30 14:00:00',
		statusName : '모집중',
		deadline : '2023-06-10 14:00:00',
		applyCount : 3,
		registerCount : 1,
		actTypeName : '교육지원',
		teenager : true,
		images : ['../../assets/images/volunteer1.jpg'],
		user_id : '1',
		updateAt : '2023-05-31 15:00:00',
	},
	{
		_id: 4,
		title: '도시락배달 봉사',
		content: '우면종합사회복지관에서 도시락 봉사를 도와주실 봉사자를 모집합니다. 궁금한 사항 있으시면 언제든 연락주세요',
		centName: '우면종합사회복지관',
		createdAt : '2023-05-30 14:00:00',
		statusName : '모집중',
		deadline : '2023-06-10 14:00:00',
		applyCount : 3,
		registerCount : 1,
		actTypeName : '교육지원',
		teenager : true,
		images : ['../../assets/images/volunteer1.jpg'],
		user_id : '1',
		updateAt : '2023-05-31 15:00:00',
	},
	{
		_id: 5,
		title: '어르신 요가 교실',
		content: '영등포치매예방센터에서 어르신 요가 교육지도를 도와주실 봉사자를 모집합니다. 궁금한 사항 있으시면 언제든 연락주세요',
		centName: '영등포치매예방센터',
		createdAt : '2023-05-30 14:00:00',
		statusName : '모집중',
		deadline : '2023-06-10 14:00:00',
		applyCount : 3,
		registerCount : 1,
		actTypeName : '교육지원',
		teenager : true,
		images : ['../../assets/images/volunteer1.jpg'],
		user_id : '1',
		updateAt : '2023-05-31 15:00:00',
	},
	{
		_id: 6,
		title: '어린이학습지 지도',
		content: '남양주아동센터에서 초등학생 1~6학년 아이들 교육지도를 도와주실 봉사자를 모집합니다. 궁금한 사항 있으시면 언제든 연락주세요',
		centName: '남양주아동센터',
		createdAt : '2023-05-30 14:00:00',
		statusName : '모집중',
		deadline : '2023-06-10 14:00:00',
		applyCount : 3,
		registerCount : 1,
		actTypeName : '교육지원',
		teenager : true,
		images : ['../../assets/images/volunteer1.jpg'],
		user_id : '1',
		updateAt : '2023-05-31 15:00:00',
	},
	{
		_id: 7,
		title: '연탄배달봉사',
		content: '지구촌복지관에서 연탄배달봉사를 도와주실 봉사자를 모집합니다. 궁금한 사항 있으시면 언제든 연락주세요',
		centName: '지구촌복지관',
		createdAt : '2023-05-30 14:00:00',
		statusName : '모집중',
		deadline : '2023-06-10 14:00:00',
		applyCount : 3,
		registerCount : 1,
		actTypeName : '교육지원',
		teenager : true,
		images : ['../../assets/images/volunteer1.jpg'],
		user_id : '1',
		updateAt : '2023-05-31 15:00:00',
	}
	,{
		_id: 8,
		title: '어린이 글쓰기 교실',
		content: '지구촌지역아동센터에서 어린이 글쓰기 교실을 도와주실 봉사자를 모집합니다. 궁금한 사항 있으시면 언제든 연락주세요',
		centName: '지구촌지역아동센터',
		createdAt : '2023-05-30 14:00:00',
		statusName : '모집중',
		deadline : '2023-06-10 14:00:00',
		applyCount : 3,
		registerCount : 1,
		actTypeName : '교육지원',
		teenager : true,
		images : ['../../assets/images/volunteer1.jpg'],
		user_id : '1',
		updateAt : '2023-05-31 15:00:00',
	},
];

export const ReviewList = [
	{
		_id: 1,
		title : '직장인 유기견 봉사활동 후기 6개월차',
		content : '저는 일주일에 1번씩 6개월 동안 유기견 봉사활동을 다녔던 직장인입니다. 봉사가 취미이기도 하고, 봉사활동 하고나면 남한테 도움을 준듯한 느낌이 들어 기분이 좋아지더라구요 이번 유기견 봉사활동도 잘 마칠 수 있었습니다.',
		images : ['사진1', '사진2'],
		volunteer_id :	'volunteer_id',
		user_id : {
			nickname: '봉사원3',
		},
	},
	{
		_id: 2,
		title : '경기도 반려동물 유기견 관리 후기',
		content : '처음 해봤던 유기견 관리 봉사였는데 좋은 경험했습니다!',
		images : ['사진1'],
		volunteer_id : 'volunteer_id',
		user_id : {
			nickname: '봉사원1',
		},
	}, 
	{
		_id: 3,
		title : '뜻깊은 경험을 해본 것 같아요~~',
		content : '견사 청소, 강아지 배변 훈련을 진행했어요. 매번 마음속으로만 생각했는데, 직접해보니까 너무 마음 따뜻해지더라구요.',
		images : [],
		volunteer_id : 'volunteer_id',
		user_id : {
			nickname: '봉사원2',
		},
	}, 
	{
		_id: 4,
		title : '할머니 요가 교실 후기',
		content : '처음 해봤던 유기견 관리 봉사였는데 좋은 경험했습니다!',
		images : ['사진1'],
		volunteer_id : 'volunteer_id',
		user_id : {
			nickname: '봉사원4',
		},
	}, 
	{
		_id: 5,
		title : '아이들과의 행복한 시간',
		content : '견사 청소, 강아지 배변 훈련을 진행했어요. 매번 마음속으로만 생각했는데, 직접해보니까 너무 마음 따뜻해지더라구요.',
		images : [],
		volunteer_id : 'volunteer_id',
		user_id : {
			nickname: '봉사원5',
		},
	}, 
	{
		_id: 6,
		title : '저는 내일도 봉사갑니다.',
		content : '저는 일주일에 1번씩 6개월 동안 유기견 봉사활동을 다녔던 직장인입니다. 봉사가 취미이기도 하고, 봉사활동 하고나면 남한테 도움을 준듯한 느낌이 들어 기분이 좋아지더라구요 이번 유기견 봉사활동도 잘 마칠 수 있었습니다.',
		images : ['사진1', '사진2'],
		volunteer_id :	'volunteer_id',
		user_id : {
			nickname: '봉사원6',
		},
	},
];

export const communityList = [
	{
		_id: 1,
		user_id: {
			nickname: '커뮤장인1',
		},
		postType: '동행구해요',
		title : '[푸른문간]에서 진행하는 에너지 취약계층을 위한 배달봉사 같이할사람!',
		content: '배달봉사 처음이라서 꼭 해보고 싶은데 아직 모집인원이 적어서 사라질까 걱정이라ㅠㅠ 같이 할 사람 아래 오픈챗으로 연락줘!',
		images: [],
		comment_id: 'comment_id',
		createdAt: '2023-05-30 13:21:10',
		updatedAt: '2023-05-30 13:25:10',
	},
	{
		_id: 2,
		user_id: {
			nickname: '커뮤장인2',
		},
		postType: '동행구해요',
		title : '한강 플러깅 봉사활동 모집합니다.',
		content: '배달봉사 처음이라서 꼭 해보고 싶은데 아직 모집인원이 적어서 사라질까 걱정이라ㅠㅠ 같이 할 사람 아래 오픈챗으로 연락줘!',
		images: [],
		comment_id: 'comment_id',
		createdAt: '2023-05-30 13:21:10',
		updatedAt: '2023-05-30 13:25:10',
	},
	{
		_id: 3,
		user_id: {
			nickname: '커뮤장인3',
		},
		postType: '동행구해요',
		title : '남양주 유기견 봉사활동 모집합니다.',
		content: '배달봉사 처음이라서 꼭 해보고 싶은데 아직 모집인원이 적어서 사라질까 걱정이라ㅠㅠ 같이 할 사람 아래 오픈챗으로 연락줘!',
		images: [],
		comment_id: 'comment_id',
		createdAt: '2023-05-30 13:21:10',
		updatedAt: '2023-05-30 13:25:10',
	},
	{
		_id: 4,
		user_id: {
			nickname: '커뮤장인4',
		},
		postType: '궁금해요',
		title : '봉사활동 추천 받아요.',
		content: '봉사활동 자체를 아예 해본적이 없어서 그런데 처음하기 좋은 봉사 추천좀!',
		images: [],
		comment_id: 'comment_id',
		createdAt: '2023-05-30 13:21:10',
		updatedAt: '2023-05-30 13:25:10',
	},
	{
		_id: 5,
		user_id: {
			nickname: '커뮤장인5',
		},
		postType: '궁금해요',
		title : '유기견 봉사 준비물',
		content: '이번에 유기견 봉사 처음가보는데 뭐 준비해가면 될까? 아 그리고 팁 같은거 있으면 알려줘!',
		images: [],
		comment_id: 'comment_id',
		createdAt: '2023-05-30 13:21:10',
		updatedAt: '2023-05-30 13:25:10',
	},
	{
		_id: 6,
		user_id: {
			nickname: '커뮤장인6',
		},
		postType: '궁금해요',
		title : '봉사 처음입니다.',
		content: '봉사 처음인데 보람찬 봉사 추천좀요.',
		images: [],
		comment_id: 'comment_id',
		createdAt: '2023-05-30 13:21:10',
		updatedAt: '2023-05-30 13:25:10',
	},
];